[versions]
agp = "8.11.1"
android-compileSdk = "36"
android-minSdk = "29"
android-targetSdk = "36"
androidxLifecycle = "2.9.1"
detekt = "1.23.8"
kotlin = "2.2.20"

[libraries]
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidxLifecycle" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }

# Plugins for build-logic
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
detekt-gradle = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

# Convention Plugins
newsflow-library-detekt = { id = "newsflow.library.detekt" }
newsflow-library-kmp-library = { id = "newsflow.library.kmp.library" }