[versions]
agp = "8.11.1"
android-compileSdk = "36"
android-minSdk = "29"
android-targetSdk = "36"
androidxLifecycle = "2.9.1"
buildKonfig = "0.15.2"
coroutines = "1.10.2"
detekt = "1.23.8"
koin = "4.1.1"
kotlin = "2.2.20"
ktor = "3.3.2"
serialization = "2.2.0"
serializationJson = "1.8.1"

[libraries]
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidxLifecycle" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Test libraries
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }

# Plugins for build-logic
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
detekt-gradle = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
build-konfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }

# Convention Plugins
newsflow-library-detekt = { id = "newsflow.library.detekt" }
newsflow-library-kmp-library = { id = "newsflow.library.kmp.library" }