[versions]
agp = "8.11.1"
android-compileSdk = "36"
android-minSdk = "29"
android-targetSdk = "36"
androidxLifecycle = "2.9.6"
coroutines = "1.10.2"
datetime = "0.6.1"
detekt = "1.23.8"
koin = "4.1.1"
kotlin = "2.2.21"
kover = "0.9.3"
ktor = "3.3.3"
mokkery = "3.0.0"
newsflowLibrary = "0.3.4"
serialization = "2.2.21"
serializationJson = "1.8.1"
turbine = "1.2.1"

[libraries]
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidxLifecycle" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Test libraries
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

# build-logic libraries
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
detekt-gradle = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kover-gradle = { group = "org.jetbrains.kotlinx", name = "kover-gradle-plugin", version.ref = "kover" }

[plugins]
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }

# Convention Plugins
newsflow-library-detekt = { id = "newsflow.library.detekt" }
newsflow-library-kmp-feature = { id = "newsflow.library.kmp.feature" }
newsflow-library-kmp-library = { id = "newsflow.library.kmp.library" }
newsflow-library-kover = { id = "newsflow.library.kover" }
newsflow-library-maven-publish = { id = "newsflow.library.maven.publish" }