blank_issues_enabled: true
contact_links:
  - name: 質問 / Questions
    url: https://github.com/kei-1111/android-template/discussions
    about: 使い方やプロジェクトに関する質問は、Discussionsで聞いてください / For questions about usage, please use Discussions